---
title: "ld_nld_mapping"
author: "Sophie"
date: "2023-12-27"
output: html_document
---



```{r}

library(sf)
library(here)
library(readxl)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(readr)
library(stringr)
```

```{r}
# input paths
data_input <- "/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/06_Data and Modelling/thesis_data/mobility/district_level/probabilities/"

data_input_w <- "/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/06_Data and Modelling/thesis_data/mobility/ward_level/"

map_input <-"/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/06_Data and Modelling/thesis_data/shapefiles/60_districts/"

map_input_w <-"/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/06_Data and Modelling/thesis_data/shapefiles/ipums_2012_wards/geo3_zw2012/"

map_input_t <- "/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/06_Data and Modelling/thesis_data/shapefiles/zwe_towns/"

map_output <-"/Users/sophieayling/Library/CloudStorage/GoogleDrive-sophie2ayling@gmail.com/My Drive/PhD/06_Data and Modelling/map_output"

```


```{r}

#read in district leave data for ld and nld 

dist_leave_probs <- read_csv(file.path(data_input,"d_comb_prob_leave_nld_elLd.csv"))

# add a variable for the difference 
dist_leave_probs$diff_prob <- dist_leave_probs$ld_prob_leave - dist_leave_probs$nld_prob_leave
```


```{r}

# read in the district level shape file for zim EPSG:20936, ID2 is district

zim_60d <- st_read(file.path(map_input, "ZWE_adm2.shp")) %>%
  st_transform(., 20936) 

plot(zim_60d["ID_2"])

```


```{r}
# join the leave probability data with the shapefile based on the district number using merge function (because that's join by attributes)

merged_data <- merge(zim_60d, dist_leave_probs, by.x = "NAME_2", by.y="label")

```

```{r}
# bring in major towns 

major_towns <- st_read(file.path(map_input_t, "Final_Zimbabwe_Towns_Version01.shp")) 
major_towns_filtered <- major_towns %>%
  filter(Show == "yes")
# Ensure that major_towns has correct GPS coordinates in columns Longitude and Latitude
# If necessary, convert major_towns_filtered into an sf object
major_towns_sf <- st_as_sf(major_towns_filtered, coords = c("LONG", "LAT"), crs = 20936 )

# Convert major_towns_sf to a data frame with explicit Longitude and Latitude columns
major_towns_coords <- major_towns_sf %>%
  mutate(Longitude = st_coordinates(.)[, 1], 
         Latitude = st_coordinates(.)[, 2])

plot(major_towns_coords["Show"=="yes"])
```

```{r}
 #now can plot the distribution of LD versus non lockdown leavers and see how they vary across the country 

plot(merged_data["nld_prob_leave"])
plot(merged_data["diff_prob"])

```
```{r}

```




```{r}
library("ggrepel")
# Ensure that both major_towns_sf and merged_data have the same CRS
# Assuming merged_data has a different CRS, let's transform the points to match the CRS of merged_data
major_towns_sf <- st_transform(major_towns_sf, crs = st_crs(merged_data))

# Define names to exclude
names_to_exclude <- c("Harari", "Machipanda", "Nyamapanda")

# Create a filtered dataset
major_towns_sf <- major_towns_sf %>%
  filter(!NAME %in% names_to_exclude)  # Exclude specified names


# Convert major_towns_sf to a data frame with explicit Longitude and Latitude columns
# This keeps the geometry in the correct CRS while also extracting coordinates
major_towns_coords <- major_towns_sf %>%
  mutate(Longitude = st_coordinates(.)[, 1], 
         Latitude = st_coordinates(.)[, 2])

# Create a list of variables (for nld and ld)
variables <- c("nld_prob_leave", "ld_prob_leave")
subtitle_labels <- c("non-lockdown", "lockdown")

# Create a list to store the ggplot objects
plots <- list()

# Create a multiplot maps
for (i in seq_along(variables)) {
  # Create a ggplot for each variable
  plot <- ggplot() +
    geom_sf(data = merged_data, aes(fill = !!sym(variables[i]))) +   # Plot the shapefile
    scale_fill_viridis_c(option = "C", direction = -1) +  # Choose a suitable color scale
    geom_point(data = major_towns_coords, aes(x = Longitude, y = Latitude), 
               color = "black", size = 0.5, inherit.aes = FALSE) +  # Add GPS points on top
    # Add labels with callout lines
    geom_segment(data = major_towns_coords, 
                 aes(x = Longitude, y = Latitude, 
                 xend = Longitude + 1.5, yend = Latitude +0.5), 
                 color = "black") +  # Callout lines (adjust xend and yend for spacing)
    geom_text(data = major_towns_coords, 
              aes(x = Longitude + 1.5, y = Latitude +0.5,
              label = NAME),  # Replace 'town_name' with the column name containing town names
              size = 2, hjust = 0, vjust = 0, color = "black") +  # Add labels near the points
  
    ggtitle("") +  # Remove default ggtitle
    ggtitle(variables[i]) +
    labs(fill = "% of pop leaving the district") +  # Rename the legend
    labs(title = "", subtitle = subtitle_labels[i], fill = "% of pop leaving the district") +
    theme_void() +
    theme(
      legend.position = "right",  # Move legend to the right
      plot.subtitle = element_text(size = 10),  # Adjust subtitle font size
      plot.caption = element_text(size = 8)  # Adjust caption font size
    )
  
  # Add the ggplot object to the list
  plots[[i]] <- plot
}

# Arrange the plots in a quadrant
final_plot <- ggarrange(plotlist = plots, ncol = 2, nrow = 1, common.legend = TRUE) +
  theme(plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"))  # Adjust margin between rows

# Annotate the figure with a title
final_plot <- annotate_figure(final_plot,
                              top = text_grob("Daily Probability of Leaving a District in Zimbabwe (weekly average)", size = 14, face = "bold", vjust = 0.5),
                              bottom = text_grob("Source: World Bank Aggregated CDR data 1st Feb - March 15th & April 1st-30th 2020", size = 10),
                              fig.lab.size = 14)

# Adjust margins and background
final_plot <- final_plot + theme(
  plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"),  # Adjust overall plot margin
  plot.background = element_rect(fill = "white", color = NA),
  panel.background = element_rect(fill = "white", color = NA)
)

# Display the final plot
print(final_plot)

# Export the final plot as a PNG with DPI set to 300
ggsave(filename = file.path(map_output, "nld_vs_ld_dist_prob_leave_with_major_towns.png"), final_plot, dpi = 300, width = 10, height = 8)
```
```{r}
## now the idea is to have one which is early and late lockdown next to the nonlockdown 
## The code below produces Ch 3 Fig 11

library("ggrepel")
# Ensure that both major_towns_sf and merged_data have the same CRS
# Assuming merged_data has a different CRS, let's transform the points to match the CRS of merged_data
major_towns_sf <- st_transform(major_towns_sf, crs = st_crs(merged_data))

# Define names to exclude
names_to_exclude <- c("Harari", "Machipanda", "Nyamapanda")

# Create a filtered dataset
major_towns_sf <- major_towns_sf %>%
  filter(!NAME %in% names_to_exclude)  # Exclude specified names


# Convert major_towns_sf to a data frame with explicit Longitude and Latitude columns
# This keeps the geometry in the correct CRS while also extracting coordinates
major_towns_coords <- major_towns_sf %>%
  mutate(Longitude = st_coordinates(.)[, 1], 
         Latitude = st_coordinates(.)[, 2])

# Create a list of variables (for nld and ld)
variables <- c("diff_eLd_nLd", "diff_lLd_nLd")
subtitle_labels <- c("pre vs. early LD", "pre vs. late LD")

# Create a list to store the ggplot objects
plots <- list()

# Create a multiplot maps
for (i in seq_along(variables)) {
  # Create a ggplot for each variable
  plot <- ggplot() +
    geom_sf(data = merged_data, aes(fill = !!sym(variables[i]))) +   # Plot the shapefile
    scale_fill_gradient2(
      low = "blue",     # Cool colors for values < 0
      mid = "white",    # Neutral midpoint at 0
      high = "red",     # Hot colors for values > 0
      midpoint = 0,     # Set the midpoint of the scale
      limits = c(-0.2, 0.2),
      name = "% of pop leaving the district",  # Legend title
      #breaks = c(-0.2, -0.1, 0, 0.1, 0.2), 
      labels = scales::percent_format(accuracy = 1)
    ) +
    geom_point(data = major_towns_coords, aes(x = Longitude, y = Latitude), 
               color = "black", size = 0.5, inherit.aes = FALSE) +  # Add GPS points on top
    # Add labels with callout lines
    geom_segment(data = major_towns_coords, 
                 aes(x = Longitude, y = Latitude, 
                 xend = Longitude + 1.5, yend = Latitude +0.5), 
                 color = "black") +  # Callout lines (adjust xend and yend for spacing)
    geom_text(data = major_towns_coords, 
              aes(x = Longitude + 1.5, y = Latitude +0.5,
              label = NAME),  # Replace 'town_name' with the column name containing town names
              size = 2, hjust = 0, vjust = 0, color = "black") +  # Add labels near the points
  
    ggtitle("") +  # Remove default ggtitle
    ggtitle(variables[i]) +
    labs(fill = "% of pop leaving the district") +  # Rename the legend
    labs(title = "", subtitle = subtitle_labels[i], fill = "% of pop leaving the district") +
    theme_void() +
    theme(
      legend.position = "right",  # Move legend to the right
      plot.subtitle = element_text(size = 10),  # Adjust subtitle font size
      plot.caption = element_text(size = 8)  # Adjust caption font size
    )
  
  # Add the ggplot object to the list
  plots[[i]] <- plot
}

# Arrange the plots in a quadrant
final_plot <- ggarrange(plotlist = plots, ncol = 2, nrow = 1, common.legend = TRUE) +
  theme(plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"))  # Adjust margin between rows

# Annotate the figure with a title
final_plot <- annotate_figure(final_plot,
                              top = text_grob("Flights vs. Reductions \n Pre (Feb 2020) vs. Early Lockdown (March 15-30th) and Pre vs. Late Lockdown (April 2020", size = 10, face = "bold", vjust = 0.5),
                              bottom = text_grob("Source: World Bank Aggregated CDR data 1st Feb - March 15th & April 1st-30th 2020", size = 10),
                              fig.lab.size = 14)

# Adjust margins and background
final_plot <- final_plot + theme(
  plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"),  # Adjust overall plot margin
  plot.background = element_rect(fill = "white", color = NA),
  panel.background = element_rect(fill = "white", color = NA)
)

# Display the final plot
print(final_plot)

# Export the final plot as a PNG with DPI set to 300
ggsave(filename = file.path(map_output, "nld_vs_elLd_dist_prob_leave_with_major_towns.png"), final_plot, dpi = 300, width = 10, height = 8)
```




```{r}

# The following code produces Figure 9 - with the non-lockdown and lockdown probability of leaving followed by the difference 

library("ggrepel")
# Ensure that both major_towns_sf and merged_data have the same CRS
# Assuming merged_data has a different CRS, let's transform the points to match the CRS of merged_data
major_towns_sf <- st_transform(major_towns_sf, crs = st_crs(merged_data))

# Define names to exclude
names_to_exclude <- c("Harari", "Machipanda", "Nyamapanda")

# Create a filtered dataset
major_towns_sf <- major_towns_sf %>%
  filter(!NAME %in% names_to_exclude)  # Exclude specified names


# Convert major_towns_sf to a data frame with explicit Longitude and Latitude columns
# This keeps the geometry in the correct CRS while also extracting coordinates
major_towns_coords <- major_towns_sf %>%
  mutate(Longitude = st_coordinates(.)[, 1], 
         Latitude = st_coordinates(.)[, 2])

# Create a list of variables (for nld and ld)
variables <- c("nld_prob_leave", "ld_prob_leave", "diff_prob")
subtitle_labels <- c("non-lockdown", "lockdown", "difference")

# Create a list to store the ggplot objects
plots <- list()

# Create a multiplot maps
for (i in seq_along(variables)) {
  # Create a ggplot for each variable
  plot <- ggplot() +
    geom_sf(data = merged_data, aes(fill = !!sym(variables[i]))) +   # Plot the shapefile
    scale_fill_viridis_c(option = "C", direction = -1) +  # Choose a suitable color scale
    geom_point(data = major_towns_coords, aes(x = Longitude, y = Latitude), 
               color = "black", size = 0.5, inherit.aes = FALSE) +  # Add GPS points on top
    # Add labels with callout lines
    geom_segment(data = major_towns_coords, 
                 aes(x = Longitude, y = Latitude, 
                 xend = Longitude + 1.5, yend = Latitude +0.5), 
                 color = "black") +  # Callout lines (adjust xend and yend for spacing)
    geom_text(data = major_towns_coords, 
              aes(x = Longitude + 1.5, y = Latitude +0.5,
              label = NAME),  # Replace 'town_name' with the column name containing town names
              size = 2, hjust = 0, vjust = 0, color = "black") +  # Add labels near the points
  
    ggtitle("") +  # Remove default ggtitle
    ggtitle(variables[i]) +
    labs(fill = "% of pop leaving the district") +  # Rename the legend
    labs(title = "", subtitle = subtitle_labels[i], fill = "% of pop leaving the district") +
    theme_void() +
    theme(
      legend.position = "right",  # Move legend to the right
      plot.subtitle = element_text(size = 10),  # Adjust subtitle font size
      plot.caption = element_text(size = 8)  # Adjust caption font size
    )
  
  # Add the ggplot object to the list
  plots[[i]] <- plot
}

# Arrange the plots in a quadrant
final_plot <- ggarrange(plotlist = plots, ncol = 3, nrow = 1, common.legend = TRUE) +
  theme(plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"))  # Adjust margin between rows

# Annotate the figure with a title
final_plot <- annotate_figure(final_plot,
                              top = text_grob("Daily Probability of Leaving a District in Zimbabwe (weekly average)", size = 14, face = "bold", vjust = 0.5),
                              bottom = text_grob("Source: World Bank Aggregated CDR data 1st Feb - March 15th & April 1st-30th 2020", size = 10),
                              fig.lab.size = 14)

# Adjust margins and background
final_plot <- final_plot + theme(
  plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"),  # Adjust overall plot margin
  plot.background = element_rect(fill = "white", color = NA),
  panel.background = element_rect(fill = "white", color = NA)
)

# Display the final plot
print(final_plot)

# Export the final plot as a PNG with DPI set to 300
ggsave(filename = file.path(map_output, "nld_vs_ld_vs_diff_dist_prob_leave_with_major_towns.png"), final_plot, dpi = 300, width = 10, height = 8)

```


```{r}
library("ggrepel")

# Ensure CRS consistency
major_towns_sf <- st_transform(major_towns_sf, crs = st_crs(merged_data))

# Define names to exclude
names_to_exclude <- c("Harari", "Machipanda", "Nyamapanda")

# Filter out specified names
major_towns_sf <- major_towns_sf %>%
  filter(!NAME %in% names_to_exclude)

# Convert to a data frame with explicit coordinates
major_towns_coords <- major_towns_sf %>%
  mutate(Longitude = st_coordinates(.)[, 1], 
         Latitude = st_coordinates(.)[, 2])

# Define variables and subtitle labels
variables <- c("nld_prob_leave", "ld_prob_leave", "diff_prob")
subtitle_labels <- c(" non-lockdown \n (probability of leaving)", "lockdown \n (probability of leaving)", "difference \n (ld-nld)")

# Create an empty list to store plots
plots <- list()

# Create the first two maps (with the same legend)

# Define min and max limits for the legend
min_value <- 0  # Set your custom minimum value
max_value <- 1  # Set your custom maximum value


for (i in 1:2) {
  plot <- ggplot() +
    geom_sf(data = merged_data, aes(fill = !!sym(variables[i]))) +
    scale_fill_viridis_c(option = "C", direction = -1, 
                         limits = c(min_value, max_value), 
                         name = NULL) + 
    geom_point(data = major_towns_coords, aes(x = Longitude, y = Latitude), color = "black", size = 0.5) +
    geom_segment(data = major_towns_coords, aes(x = Longitude, y = Latitude, xend = Longitude + 1.5, yend = Latitude + 0.5), color = "black") +
    geom_text(data = major_towns_coords, aes(x = Longitude + 1.5, y = Latitude + 0.5, label = NAME), size = 2, hjust = 0, vjust = 0, color = "black") +
    labs(subtitle = subtitle_labels[i]) +
    theme_void() +
    theme(
      legend.position = "bottom",  # Position the legend to the right
      legend.title = element_text(size = 8),  # Reduce legend title size
      legend.text = element_text(size = 7),  # Reduce legend text size
      legend.key.size = unit(0.5, "cm"),  # Reduce the legend key size
      legend.spacing.y = unit(0.2, "cm"),  # Adjust vertical spacing between legend keys
      plot.subtitle = element_text(size = 10),  # Subtitle font size
      plot.caption = element_text(size = 8),
      panel.backgorund = element_rect(fill= "white", color=NA),
      plot.background = element_rect(fill="white", color=NA)
    )

  plots[[i]] <- plot
}

# Create the third map (with a different legend for the "difference" variable)
plot_diff <- ggplot() +
  geom_sf(data = merged_data, aes(fill = !!sym(variables[3]))) +
  scale_fill_viridis_c(option = "D", direction = 1, name = NULL) +
  geom_point(data = major_towns_coords, aes(x = Longitude, y = Latitude), color = "black", size = 0.5) +
  geom_segment(data = major_towns_coords, aes(x = Longitude, y = Latitude, xend = Longitude + 1.5, yend = Latitude + 0.5), color = "black") +
  geom_text(data = major_towns_coords, aes(x = Longitude + 1.5, y = Latitude + 0.5, label = NAME), size = 2, hjust = 0, vjust = 0, color = "black") +
  labs(subtitle = subtitle_labels[3]) +
  theme_void() +
  theme(
    legend.position = "bottom",  # Position the legend to the right
    legend.title = element_text(size = 8),  # Reduce legend title size
    legend.text = element_text(size = 7),  # Reduce legend text size
    legend.key.size = unit(0.5, "cm"),  # Reduce the legend key size
    legend.spacing.y = unit(0.2, "cm"),  # Adjust vertical spacing between legend keys
    plot.subtitle = element_text(size = 10),  # Subtitle font size
    plot.caption = element_text(size = 8),
    panel.backgorund = element_rect(fill= "white", color=NA),
    plot.background = element_rect(fill="white", color=NA)
      )

# Add the third plot to the list
plots[[3]] <- plot_diff

# Arrange the plots with separate legends
final_plot <- ggarrange(plotlist = plots, ncol = 3, nrow = 1)

# Annotate the figure with a title
final_plot <- annotate_figure(final_plot,
                              top = text_grob("Daily Probability of Leaving a District in Zimbabwe (weekly average)", 
                                              size = 14, face = "bold", vjust = 0.5),
                              bottom = text_grob("Source: World Bank Aggregated CDR data 1st Feb - March 15th & April 1st-30th 2020", 
                                                 size = 10))


# Export the final plot as a PNG with DPI set to 300
ggsave(filename = file.path(map_output, "nld_vs_ld_vs_diff_dist_prob_leave_with_major_towns.png"), 
       plot = final_plot, dpi = 300, width = 15, height = 8, bg= "white")
       
# Display the final plot
print(final_plot)
```

```{r}
# Do the same for ward data 
# read in the ward level shape file IPUMS 402 wards

zim_402w <- st_read(file.path(map_input_w, "geo3_zw2012.shp")) %>%
  st_transform(., 20936) 

#plot(zim_402w["IPUM2012"])

```

```{r}

# convert the IPUM column to numeric 

zim_402w <- zim_402w %>%
  mutate(ward_id = as.numeric(as.character(IPUM2012)))  # Replace 'string_var' with your column name

```

```{r}
#read in ward leave data for ld and nld 

ward_leave_probs <- read_csv(file.path(data_input_w,"stay_leave_comb.csv"))

# create the difference variable 
ward_leave_probs$diff_prob <- ward_leave_probs$prob_leave_ld - ward_leave_probs$prob_leave_nld

#create column with same wardid format from source
ward_leave_probs <- ward_leave_probs %>%
  mutate(ward_id = as.numeric(as.character(source)))  # Replace 'string_var' with your column name

ward_leave_probs <- ward_leave_probs %>%
  mutate(
    cleaned_var = str_remove(source, "^w_"),  # Remove the prefix
    ward_id = as.numeric(cleaned_var)        # Convert to numeric
  )
```
```{r}
# now merge the two 
# join the leave probability data with the shapefile based on the ward number using merge function (because that's join by attributes)

merged_data_w <- left_join(zim_402w, ward_leave_probs, by = "ward_id")
```

```{r}

# Create a list of variables (for nld and ld)
variables <- c("prob_leave_nld", "prob_leave_ld")
subtitle_labels <- c("non-lockdown", "lockdown")  # New subtitle labels

# Create a list to store the ggplot objects
plots <- list()

# Create a multiplot maps
for (i in seq_along(variables)) {
  # Create a ggplot for each variable
  plot <- ggplot() +
    geom_sf(data = merged_data_w, aes(fill = !!sym(variables[i])), color = NA) +
    scale_fill_viridis_c(option = "D", direction = -1, na.value = "grey") +  # Shade missing values in grey
    ggtitle("") +  # Remove default ggtitle
    ggtitle(variables[i]) +
    labs(fill = "% of pop leaving the ward") +  # Rename the legend
    labs(title = "", subtitle = subtitle_labels[i], fill = "% of pop leaving the ward") +
    theme_void() +
    theme(
      #plot.title = element_text(margin = margin(b = 10)),  # Adjust title margin
      legend.position = "right",  # Move legend to the right
      # Add a subtitle with custom labels
      plot.subtitle = element_text(size = 10),  # Adjust subtitle font size
      plot.caption = element_text(size = 8),  # Adjust caption font size
      labs(subtitle = subtitle_labels[i])  # Use custom subtitle labels
  
    )

  # Add the ggplot object to the list
  plots[[i]] <- plot
}

# Arrange the plots in a quadrant
final_plot <- ggarrange(plotlist = plots, ncol = 2, nrow = 1, common.legend=TRUE)+
  theme(plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"))  # Adjust margin between rows

# Annotate the figure with a title
final_plot <- annotate_figure(final_plot,
                              top = text_grob("Daily Probability of Leaving a Ward in Zimbabwe (weekly average)", size = 14, face = "bold", vjust=0.5),
                              bottom = text_grob("Source: World Bank Aggregated CDR data 1st Feb -  March 15th & April 1st-30th 2020", size = 10),
                               fig.lab.size = 14)


# Increase the size of individual plots
final_plot <- final_plot + theme(
  plot.margin = margin(0.5, 0.5, 1, 0.5, "cm"),  # Adjust overall plot margin
  plot.background = element_rect(fill = "white", color = NA),
  panel.background = element_rect(fill = "white", color = NA)
)



# Display the final plot
print(final_plot)

# Export the final plot as a PNG with DPI set to 300
ggsave(filename =file.path(map_output, "nld_vs_ld_ward_prob_leave.png"), final_plot, dpi = 300, width = 10, height = 8)

```

```{r}

```
```{r}
library(ggplot2)
library(ggpubr)
library(viridis)

# Compute global limits for the scale
global_max <- max(c(dist_leave_probs$diff_prob, ward_leave_probs$diff_prob), na.rm = TRUE)
global_min <- min(c(dist_leave_probs$diff_prob, ward_leave_probs$diff_prob), na.rm = TRUE)


# Create individual plots for each dataset
plot_dist_leave_prob <- ggplot() +
  geom_sf(data = merged_data, aes(fill = diff_prob)) +
  scale_fill_viridis_c(
    option = "C",
    direction = 1,
    na.value = "grey",
    #limits = c(-max(abs(dist_leave_probs$diff_prob), na.rm = TRUE), 0)
    limits = c(global_min, global_max)
  ) +
  labs(fill = "Difference", title = "District-Level Difference") +
  theme_void() +
  theme(
    legend.position = "right",
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 10)
  )

plot_ward_leave_prob <- ggplot() +
  geom_sf(data = merged_data_w, aes(fill = diff_prob), color=NA) +
  scale_fill_viridis_c(
    option = "C",
    direction = 1,
    na.value = "grey",
    #limits = c(-max(abs(ward_leave_probs$diff_prob), na.rm = TRUE), 0)
    limits = c(global_min, global_max)
  ) +
  labs(fill = "Difference", title = "Ward-Level Difference") +
  theme_void() +
  theme(
    legend.position = "right",
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 10)
  )

# Combine the plots side by side
combined_plot <- plot_grid(plot_dist_leave_prob, plot_ward_leave_prob, ncol = 2)

# Annotate the figure with a title
combined_plot <- annotate_figure(combined_plot,
  top = text_grob("Comparison of Difference Probabilities of Leaving: Reductions Lockdown vs. Non-Lockdown \n at District & Ward Level", size = 12, face = "bold", vjust = 0.5),
  bottom = text_grob("Source: World Bank Aggregated CDR data", size = 10, vjust = 0.5),
  fig.lab.size = 14
)

# Display the final plot
print(combined_plot)

# Export the final plot as a PNG with DPI set to 300
ggsave(filename = file.path(map_output, "dist_vs_ward_diff_prob.png"), 
       plot= combined_plot, 
       dpi = 300, 
       width = 12, 
       height = 6, 
       bg = "white")
```


